### ISSUE TITLE
Write on-chain transaction tests for ccv

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/cardano-constitution-voting-app#25]
Write on-chain transaction tests for ccv

Pls add more details @mesudip 

Todo: 
- [x] Add test to use kuber and submit the poll results on-chain. 
- [x] Validate the created tx-metadata.

**Comment by mesudip** [comment]
Test is implemented and passing
https://cardanoapi.github.io/ccv-test-reports/integration-tests/75/#behaviors/2f6a747cd16fc1b8fd1977b0c18b5c2e/6ae1506f64ac28b9/
